# Generated by Django 4.2.5 on 2023-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_client_user_mailing_user_mailinglog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
    ]
